#!/usr/bin/env sh
# (c) Copyright 2016 DataNexus Inc.  All Rights Reserved. 
# nifi registry deployment wrapper

: "${AWS_PROFILE:=datanexus}" && export AWS_PROFILE=$AWS_PROFILE    # sets this to a reasonable ~/.aws/credentials default
: "${AZURE_PROFILE:=datanexus}" && export AZURE_PROFILE="$AZURE_PROFILE"    # sets this to a reasonable ~/.azure/credentials default


if [ $# -eq 0 ] || [ "$1" = "-h" ] ; then
    printf "Usage:  deploy [-h]\\thelp\\n"
    printf "\\t deploy [INVENTORY TENANT PROJECT CLOUD REGION DOMAIN CLUSTER]\\tdeploy %s overlay with the specified values\\n" "$application"
    printf "Example: deploy datanexus demo aws us-east-1 development none\\n"
    exit 0
fi

tenant=`/usr/bin/basename ${2}`   # derive tenant name from the path
application=nifi_registry           # application overlay to deploy

./provision-nifiregistry --inventory=${1} --tags "$application" -e "tenant_config_path=${2} project=${3} cloud=${4} region=${5} domain=${6} cluster=${7} tenant=${tenant} application=${application}"
