# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# apply AWS nifi registry security group rules for multi-interface systems
---
- name: NIFI REGISTRY ({{ cloud }}) | discovering nifi registry instances
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: running
      "tag:Tenant": "{{ tenant }}"
      "tag:Project": "{{ project }}"
      "tag:Domain": "{{ domain }}"
      "tag:Application": 'nifi_registry'
      # "tag:Cluster": "{{ cluster | default ('a') }}"
      "tag:Dataflow": "{{ dataflow | default('none') }}"
  register: all_registry_nodes
  when:
    - cloud == 'aws'
    - "'nifi_registry' in groups | default([])"
  
- block:

  # construct list of all interfaces attached to nifi registry nodes
  - set_fact:
      registry_interfaces: "{{ all_registry_nodes.instances | map(attribute='network_interfaces') | list }}"

  # apply internal SSH rule
  - name: NIFI REGISTRY ({{ cloud }}) | applying ssh security rules to interface 0
    ec2_eni:
      region: "{{ region }}"
      eni_id: "{{ item.network_interface_id }}"
      security_groups:
        - "{{ sg_ssh_private.security_groups.0.group_id }}"
    with_items: "{{ registry_interfaces }}"
    when: item.attachment.device_index == 0
  
  # apply nifi rules
  - name: NIFI REGISTRY ({{ cloud }}) | applying nifi security rules to interface 1
    ec2_eni:
      region: "{{ region }}"
      eni_id: "{{ item.network_interface_id }}"
      security_groups:
        - "{{ sg_nifi_registry_external.group_id }}"
    with_items: "{{ registry_interfaces }}"
    when: item.attachment.device_index == 1
    
  when:
    - "'nifi_registry' in groups | default([])"
    - groups.nifi_registry | length > 0
