# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# OS tasks that occur post-boot and pre-appplication installation
---
# shell limits
- import_tasks: limits.yml
# kernel tuning
- import_tasks: kernel.yml
# vm tuning
- import_tasks: vm.yml

- name: NIFI REGISTRY ({{ cloud }}) | turning off vm swap
  sysctl:
    name: vm.swappiness
    value: 0
    state: present
    reload: yes
  become: yes
    