# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
---
- name: NIFI REGISTRY ({{ cloud }}) (TUNING) | jvm heap size is...{{ ((jvm_heap | default('auto')) | int != 0) | ternary ((jvm_heap),('automatic')) }}
  set_fact:
    heap_req="{{ ((jvm_heap | default('auto')) | int != 0) | ternary ((jvm_heap),((ansible_memtotal_mb | int / 2048) | round(0,'floor') | int)) }}"    

# this calculates half the total memory (rounded down) for the JVM; for nifi this should max out at 5g
- name: NIFI REGISTRY ({{ cloud }}) (TUNING) | setting jvm heap to {{ ((heap_req | int) <= 5) | ternary((heap_req),(5)) }}g
  set_fact: jvm_heap_mem="{{ ((heap_req | int) <= 5) | ternary((heap_req),(5)) }}"

- name: NIFI REGISTRY ({{ cloud }}) (TUNING) | validating {{ jvm_heap_mem }}gb needed <= {{ ((ansible_memtotal_mb | int / 2048) | round(0,'floor') | int) }}gb total
  assert:
    that:
      - (jvm_heap_mem | int) <= ((ansible_memtotal_mb | int / 2048) | round(0,'floor') | int) 
    fail_msg: "heap space inadequate: allocate more RAM, decrease requested heap space, or set 'jvm_heap' to 'auto'"
    success_msg: "system has enough heap space"
